name: send notifications

on:
  release:
    types:
      - published
  workflow_call:
    secrets:
        TELEGRAM_INFO_BOT_ID:
            description: 'telegram bot id'
            required: true
        TELEGRAM_INFO_CHANNEL_ID:
            description: 'channel id'
            required: true

jobs:
  notify_telegram:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install jq
      - name: "post to telegram"
        shell: bash
        env:
          TELEGRAM_BOT_SECRET: ${{ secrets.TELEGRAM_INFO_BOT_ID }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_INFO_CHANNEL_ID }}
        run: |
          echo '#!/usr/bin/env bash' > send_update.sh
          
          echo '{"chat_id":'"$TELEGRAM_CHAT_ID"',"text":' > info_message
          (
            printf '🤖 Lifeblood-Manager update ${{ github.ref_name }}!\n\n'
            git tag -l --format='%(contents)' ${{ github.ref_name }}
            printf "\n\n#manager"
          ) | jq -Rsa . >> info_message
          echo -e \\n'#manager' >> info_message
          echo '}' >> info_message
          
          # only for curl8
          # curl --variable '%TELEGRAM_BOT_SECRET' --expand-url="https://api.telegram.org/bot{{TELEGRAM_BOT_SECRET}}/sendMessage" --json @info_message
          
          curl -s -X POST -H "Content-Type:application/json" "https://api.telegram.org/bot""${TELEGRAM_BOT_SECRET}""/sendMessage" --data @info_message
          rm info_message
