on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

name: Tests

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_target:
          - "x86_64-unknown-linux-gnu"
          - "x86_64-pc-windows-gnu"
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.build_target }}
          override: true
      - name: run tests
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ matrix.build_target }}